#!/bin/sh

# Uncrustify check
echo "pre-commit: Running uncrustify check..."
if ! cmake --build build -t uncrustify-check
then
    echo "pre-commit: Aborting commit due to failed uncrustify check"
    exit 1
else
    echo "pre-commit: Uncrustify check passed"
    exit 0
fi