#ifndef GREEN_LINE_BLOCKS_H
#define GREEN_LINE_BLOCKS_H

#include "wayside_controller.h"

namespace wayside_controller
{

const std::vector<WaysideBlock> kGreenLineBlocksWayside1 = {
    WaysideBlock(53, 54, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 0, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(54, 55, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 1, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(55, 56, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 2, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(56, 57, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 3, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(57, 58, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 4, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(58, 59, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 5, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(59, 60, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 6, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(60, 61, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 7, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(61, 62, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 8, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(62, 63, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 9, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(63, 64, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 10, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(64, 65, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 11, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(65, 66, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 12, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(66, 67, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 13, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(67, 68, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 14, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(68, 69, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 15, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(69, 70, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 16, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(70, 71, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 17, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(71, 72, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 18, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(72, 73, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 19, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(73, 74, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 20, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(74, 75, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 21, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(75, 76, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 22, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(76, 77, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 23, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(77, 78, 76, 101, types::BlockDirection::BLOCKDIRECTION_BIDIRECTIONAL, 24, 78, 0, true, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(78, 79, 0, 0, types::BlockDirection::BLOCKDIRECTION_BIDIRECTIONAL, 25, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(79, 80, 0, 0, types::BlockDirection::BLOCKDIRECTION_BIDIRECTIONAL, 26, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(80, 81, 0, 0, types::BlockDirection::BLOCKDIRECTION_BIDIRECTIONAL, 27, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(81, 82, 0, 0, types::BlockDirection::BLOCKDIRECTION_BIDIRECTIONAL, 28, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(82, 83, 0, 0, types::BlockDirection::BLOCKDIRECTION_BIDIRECTIONAL, 29, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(83, 84, 0, 0, types::BlockDirection::BLOCKDIRECTION_BIDIRECTIONAL, 30, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(84, 85, 0, 0, types::BlockDirection::BLOCKDIRECTION_BIDIRECTIONAL, 31, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(85, 86, 86, 100, types::BlockDirection::BLOCKDIRECTION_BIDIRECTIONAL, 32, 79, 1, true, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(86, 87, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 33, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(87, 88, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 34, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(88, 89, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 35, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(89, 90, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 36, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(90, 91, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 37, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(91, 92, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 38, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(92, 93, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 39, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(93, 94, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 40, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(94, 95, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 41, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(95, 96, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 42, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(96, 97, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 43, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(97, 98, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 44, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(98, 99, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 45, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(99, 100, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 46, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(100, 85, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 47, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(101, 102, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 48, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(102, 103, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 49, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(103, 104, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 50, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(104, 105, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 51, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(105, 106, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 52, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(106, 107, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 53, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(107, 108, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 54, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(108, 109, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 55, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(109, 110, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 56, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(110, 111, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 57, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(111, 112, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 58, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(112, 113, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 59, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(113, 114, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 60, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(114, 115, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 61, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(115, 116, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 62, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(116, 117, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 63, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(117, 118, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 64, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(118, 119, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 65, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(119, 120, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 66, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(120, 121, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 67, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(121, 122, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 68, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(122, 123, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 69, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(123, 124, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 70, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(124, 125, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 71, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(125, 126, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 72, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(126, 127, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 73, 0, 0, false, false, IoSignal::IOSIGNAL_LOW),
    WaysideBlock(127, 128, 0, 0, types::BlockDirection::BLOCKDIRECTION_UNIDIRECTIONAL, 74, 0, 0, false, false, IoSignal::IOSIGNAL_LOW)};

const std::vector<BlockOutputs> kGreenLineBlockOutputsWayside1 = {
    {77, true, 0, false, 0, false, 0, 0},
    {85, true, 1, false, 0, false, 0, 0},
    {76, false, 0, false, 0, true, 2, 3},
    {100, false, 0, false, 0, true, 4, 5},
    {108, false, 0, true, 6, false, 0, 0}
};

} // namespace wayside_controller

#endif // GREEN_LINE_BLOCKS_H