import { HorizontalBox, Button, GroupBox, Switch, TabWidget, StandardTableView, LineEdit, VerticalBox, StandardListView, ScrollView, ComboBox } from "std-widgets.slint";

component TransitSystem inherits Rectangle {
    background: #252525;
    border-radius: 10px;
    preferred-height: 300px;
    in-out property <[[StandardListViewItem]]> block_data;
    in-out property <string> block_id;
    in-out property <bool> mode;
    in-out property <bool> switch;

    VerticalLayout {
        padding-top: 10px;
        HorizontalLayout {
            padding-top: 7px;
            padding-left: 15px;
            spacing: 20px;
            Text { 
                font-size: 20px;
                font-weight: 500;
                text: "Transit System";
            }
            HorizontalLayout {
                Text {font-size: 20px; text: "Time: ";}
                Rectangle {
                    border-radius: 5px;
                    y: -3px;
                    width: 120px;
                    height: 35px;
                    border-width: 2px;
                    border-color: #4d4d4d;
                    Text {text: "hh:mm:ss";}
                }
            }
            HorizontalLayout {
                Text {font-size: 20px;text: "Throughput: ";}
                Rectangle {
                    border-radius: 5px;
                    y: -3px;
                    width: 120px;
                    height: 35px;
                    border-width: 2px;
                    border-color: #4d4d4d;
                    Text {text: "Train/hr/line";}
                }
            }
            HorizontalLayout {
                alignment: end;
                padding-right: 15px;
                ComboBox {
                    y: -3px;
                    model: [@tr("Simulation Speed"), @tr("x1"), @tr("x10"), @tr("x50")];
                }
            }
        }
        VerticalLayout {
            padding: 15px;
            StandardTableView {
                columns: [
                    { title: @tr("Section") },
                    { title: @tr("Block") },
                    { title: @tr("Mode") },
                    { title: @tr("Switch") },
                    { title: @tr("Occupany") },
                    { title: @tr("Failure") },
                ];
                rows: block_data;
            }
        }
        ManageBlock := HorizontalLayout {
            alignment: start;
            padding: 15px;
            spacing: 10px;
            LineEdit {
                width: 120px;
                height: 30px;
                placeholder-text: @tr("Block");
                edited(input) => { block_id = input }
            }
            HorizontalLayout {
                Switch {
                    toggled => {mode = !mode}
                }
                Text {text:"  Maintenance Mode"; y: 7px;}
            }
            HorizontalLayout {
                Switch {
                    toggled => {switch = !switch}
                }
                Text {text:" Switch"; y: 7px;}
            }
        }
    }
}

component TrainSchedule inherits Rectangle {
    background: #252525;
    border-radius: 10px;
    preferred-width: 150px;
    preferred-height: 400px;
    in-out property <[[StandardListViewItem]]> train_schedules;
    VerticalLayout {
        alignment: stretch;
        padding-top: 10px;
        HorizontalLayout {
            padding-left: 15px;
            spacing: 20px;
            Text { 
                font-size: 20px;
                font-weight: 500;
                text: "Train Schedule";
            }
        }
        VerticalLayout {
            padding: 15px;
            StandardTableView {
                columns: [
                    { title: @tr("Train") },
                    { title: @tr("Position") },
                    { title: @tr("ETA") },
                    { title: @tr("DST(s)") },
                ];
                rows: train_schedules;
            }
        }
    }
}

component ManualMode inherits Rectangle {
    in-out property <int> train_id;
    in-out property <string> destination;
    in-out property <string> arrival_time;
    in-out property <[string]> stations;
    callback manual-dispatch();
    VerticalLayout {
        padding: 10px;
        spacing: 10px;
        HorizontalLayout {
            alignment: start;
            Text { font-size: 15px; text: "Train:            ";}
            Rectangle {width: 10px;}
            ComboBox {
                height: 30px;
                y: -3px;
            } 
        }
        HorizontalLayout {
            alignment: start;
            Text { font-size: 15px; text: "Stations:       ";}
            Rectangle {width: 10px;}
            ComboBox {
                height: 30px;
                y: -3px;
                model: stations;
            } 
        }
        HorizontalLayout {
            alignment: start;
            Text { font-size: 15px;text: "Destination:  ";}
            Rectangle {width: 10px;}
            LineEdit {
                height: 30px;
                y: -3px;
                edited(input) => {destination = input}
            } 
        }
        HorizontalLayout {
            alignment: start;
            Text { font-size: 15px;text: "Arrival Time: ";}
            Rectangle {width: 10px;}
            LineEdit {
                height: 30px;
                placeholder-text: @tr("10:00:00");
                edited(input) => {arrival_time = input}
            } 
        }
        VerticalLayout {
            alignment: end; 
            Button { 
                max-height: 30px;
                preferred-width: 250px;
                text: "DISPATCH";
                clicked => {manual-dispatch()}
            } 
        }
    }
}

component AutomaticMode inherits Rectangle {
    in-out property<string> fileName: "";
    callback choose-file();
    callback parse-file();
    VerticalLayout {
        padding: 10px;
        spacing: 10px;
        HorizontalLayout {
            alignment: start;
            Text { text: "Choose File: ";}
            Rectangle {width: 10px;}
            Rectangle {
                border-radius: 5px;
                y: -3px;
                width: 150px;
                height: 25px;
                border-width: 2px;
                border-color: #4d4d4d;
                Text {text: fileName;}
            } 
        }
        HorizontalLayout {
            Button { 
                max-height: 30px;
                text: "Open File";
                clicked => {choose-file()}
            }
        }
        
        VerticalLayout {
            alignment: end; 
            Button { 
                max-height: 30px;
                preferred-width: 250px;
                text: "DISPATCH";
                clicked => {parse-file()}
            } 
        }       
    }
}

component Dispatch inherits Rectangle {
    property <bool> automatic_mode: true;
    in-out property<string> fileName: "";
    in-out property <int> train_id;
    in-out property <string> destination;
    in-out property <string> arrival_time;
    in-out property <[string]> stations;

    callback choose-file();
    callback parse-file();
    callback manual-dispatch();

    background: #252525;
    border-radius: 10px;
    
    VerticalLayout {
        padding: 10px;
        spacing: 15px;
        alignment: stretch;
        Rectangle {
            height: 30px;
            // background: red;
            HorizontalLayout {
                Text { 
                    font-size: 20px;
                    font-weight: 500;
                    text: "Dispatch";
                }
            }
        }
        Rectangle {
            height: 30px;
            // background: green;
            HorizontalLayout {
                
                Button {
                    padding: 10px;
                    height: 35px;
                    clicked => {automatic_mode = !automatic_mode;}
                    text: automatic_mode ? "Automatic Mode" : "Manual Mode";
                }
            }
        }

        if(automatic_mode == true) : AutomaticMode {
            choose-file => {root.choose-file()}
            parse-file => {root.parse-file()}
            fileName: fileName;
        }
        if(automatic_mode == false) : ManualMode {
            train_id <=> train_id;
            stations: stations;
            destination <=> destination;
            arrival_time <=> arrival_time;
            manual-dispatch => {manual-dispatch()}
        }    
    }
}

component TBInputs inherits Rectangle {
    in-out property <string> block_occupancy;

    in-out property <string> confirm_occupancy_message;
    // Callbacks
    callback send_occupancy_signal();
    callback send_failure_signal();
    VerticalLayout {
        padding: 10px;
        spacing: 10px;
        WaysideOccupancy := VerticalLayout {
            spacing: 10px;
            Text {font-size: 20px; text: "Wayside Occupancy Signal:";}
            LineEdit {
                height: 50px;
                placeholder-text: @tr("Block Number");
                edited(input) => {block_occupancy = input}
            }
            Button {
                height: 40px;
                text: "Send Occupancy Signal";
                clicked => {send_occupancy_signal()}
            }
            Text {
                text: confirm_occupancy_message;
            }
            Button {
                height: 40px;
                text:  "Send Failure Signal";
                clicked => {
                    send_failure_signal();
                }
            }
            Text {
                text: confirm_occupancy_message;
            }
        }
    }
}

export component CtcUi inherits Window {
    in-out property <string> selected_fileName;
    in-out property <int> train_id;
    in-out property <[[StandardListViewItem]]> block_data;
    in-out property <[[StandardListViewItem]]> train_schedules;
    in-out property <string> destination;
    in-out property <string> arrival_time;
    in-out property <string> maintenance_section;
    in-out property <string> maintenance_block;

    //Transit System
    in-out property <bool> maintenance_mode;
    in-out property <bool> switch_state;
    in-out property <string> failure_signal;

    //Dispatch 
    in-out property <[string]> stations;

    //TestBench
    in-out property <string> block_occupancy;
    in-out property <bool> occupancy;

    in-out property <int> authority;
    in-out property <int> suggested_speed;
    in-out property <string> dwell_time;
    in-out property <string> confirm_occupancy_message;
    in-out property <string> confirm_output_message;
    in-out property <string> confirm_maintenance_message;
    in-out property <string> confirm_switch_message;
    in-out property <string> confirm_automatic_dispatch;

    callback send_occupancy();
    callback print-output-to-wayside();
    callback print-maintenance-message();
    callback print-switch-message();
    callback print-automatic-dispatch();
    callback send-failure-signal();

    callback choose-file();
    callback parse-file();
    callback manual-dispatch();

    title: "CTC Office";
    preferred-width: 600px;
    preferred-height: 600px;
    TabWidget {
        Tab {
            title: @tr("CTC Home");
            
            VerticalLayout {
                padding: 15px;
                spacing: 15px;
                alignment: stretch;
                TransitSystem {
                    block_data: block_data;
                } // Transit System Top Widget
                HorizontalLayout { // Bottom Widget Containing Train Schedule and Dispatch
                    spacing: 15px;
                    alignment: stretch;
                    TrainSchedule {
                        train_schedules <=> train_schedules;
                    }
                    Dispatch { // Bottom Right Dispatch
                        fileName: selected_fileName;
                        choose-file => {root.choose-file();}
                        parse-file => {root.parse-file()}
                        stations <=> stations;
                        train_id <=> train_id;
                        destination <=> destination;
                        arrival_time <=> arrival_time;
                        manual-dispatch => {root.manual-dispatch()}
                    }
                }   
            }
        }
        Tab {
            title: @tr("Test Bench");
            HorizontalLayout {
                padding: 15px;
                spacing: 20px;
                Rectangle {
                    background: #252525;
                    border-radius: 10px;
                    VerticalLayout {
                        alignment: start;
                        padding: 10px;
                        padding-left: 15px;
                        Text {
                            font-size: 20px;
                            font-weight: 500;
                            text: "Inputs";
                        }
                        TBInputs {
                            block_occupancy <=> block_occupancy;
                            confirm_occupancy_message: confirm_occupancy_message;
                            send_occupancy_signal => {root.send_occupancy()}
                            send_failure_signal => {root.send-failure-signal()}
                        }     
                    }
                } 
                Rectangle {
                    background: #252525;
                    border-radius: 10px;
                    VerticalLayout {
                        alignment: start;
                        padding: 10px;
                        padding-left: 15px;
                        Text {
                            font-size: 20px;
                            font-weight: 500;
                            text: "Outputs";
                        }
                        VerticalBox {
                            padding-bottom: 20px;
                            Text {
                                font-size: 20px;
                                text: "Train: \{root.train_id}";
                            }
                            Text {
                                font-size: 20px;
                                text: "Suggested Speed (m/s): \{root.suggested_speed}";
                            }
                            Text {
                                font-size: 20px;
                                text: "Authority (# blocks): \{root.authority}";
                            }
                        }
                        VerticalBox {
                            padding-bottom: 20px;
                            Text {
                                font-size: 20px;
                                text: "Section: \{maintenance_mode ? maintenance_section : ""}";
                            }
                            Text {
                                font-size: 20px;
                                text: "Block: \{maintenance_mode ? maintenance_block : ""}";
                            }
                            Text {
                                font-size: 20px;
                                text: "Mainteance Signal: \{maintenance_mode ? "True" : "False" }" ;
                            }
                        }
                        VerticalBox {
                            padding-bottom: 20px;
                            Text {
                                font-size: 20px;
                                text: "Section: \{switch_state ? maintenance_section : ""}";
                            }
                            Text {
                                font-size: 20px;
                                text: "Block: \{switch_state ? maintenance_block : ""}";
                            }
                            Text {
                                font-size: 20px;
                                text: "Switch Signal: \{switch_state ? "True" : "False"}";
                            }
                        }
                    }
                }    
            }
        }
    }
}


