import { Button, VerticalBox } from "std-widgets.slint";

import { CtcUi } from "ctc.slint";
import { WaysideControllerUi } from "waysidecontroller.slint";
import { TrackModelUi } from "trackmodel.slint";
import { TrainModelUi } from "trainmodel.slint";
import { TrainControllerUi } from "traincontroller.slint";

export component Launcher inherits Window {

    callback launch-ctc-window();
    callback launch-wayside-controller-window();
    callback launch-track-model-window();
    callback launch-train-model-window();
    callback launch-train-controller-window();

    title: "Orient Express Launcher";
    width: 400px;
    height: 400px;
    VerticalBox {
        padding: 20px;
        Text {
            text: "Orient Express Launcher";
            padding: 10px;
        }

        Button {
            text: "CTC";
            clicked => {
                root.launch-ctc-window();
            }
        }

        Button {
            text: "Wayside Controller";
            clicked => {
                root.launch-wayside-controller-window();
            }
        }

        Button {
            text: "Track Model";
            clicked => {
                root.launch-track-model-window();
            }
        }

        Button {
            text: "Train Model";
            clicked => {
                root.launch-train-model-window();
            }
        }

        Button {
            text: "Train Controller";
            clicked => {
                root.launch-train-controller-window();
            }
        }
    }
}

export component CtcWindow inherits Dialog {
    title: "CTC";
    CtcUi { }
}

export component WaysideControllerWindow inherits Dialog {
    title: "Wayside Controller";
    WaysideControllerUi { }
}

export component TrackModelWindow inherits Dialog {
    title: "Track Model";
    TrackModelUi { }
}

export component TrainModelWindow inherits Dialog {
    title: "Train Model";
    TrainModelUi { }
}

export component TrainControllerWindow inherits Dialog {
    title: "Train Controller";
    TrainControllerUi { }
}
