import { HorizontalBox, TextEdit, Button, GroupBox, Switch, TabWidget, StandardTableView, LineEdit, VerticalBox, ComboBox } from "std-widgets.slint";

component TrackInput inherits Rectangle {
    in-out property<string> fileName: "";
    callback choose-file();
    callback parse-file();
    VerticalLayout {
        padding: 10px;
        spacing: 10px;
        HorizontalLayout {
            alignment: start;
            Text { font-size: 20px; text: "Choose Track Layout File: ";}
            Rectangle {width: 10px;}
            Rectangle {
                border-radius: 5px;
                y: -3px;
                width: 150px;
                height: 25px;
                border-width: 2px;
                border-color: #4d4d4d;
                Text {text: fileName;}
            } 
        }
        HorizontalLayout {
            Button {
                max-width: 400px;
                max-height: 30px;
                text: "Open File";
                clicked => {choose-file()}
            }
        }
        HorizontalLayout {
            Button { 
                max-width: 400px;
                max-height: 30px;
                text: "Execute";
                clicked => {parse-file()}
            } 
        }       
    }
}
export component TrackModelUi inherits Window {
    min-height: 950px;
    min-width: 1200px;
    in-out property <string> base_path;
    in-out property <string> train_id;
    in-out property <string> selected_fileName;
    in-out property <string> train_block;
    in-out property <string> external_temp;
    in-out property <string> passengers_deboarding;
    in-out property <int> switch_block;
    in-out property <bool> switch_bool;
    in-out property <int> crossing_block;
    in-out property <bool> crossing_bool;
    in-out property <string> green_block;
    in-out property <bool> green_bool;
    in-out property <string> yellow_block;
    in-out property <bool> yellow_bool;
    in-out property <string> red_block;
    in-out property <bool> red_bool;
    in-out property <string> brail_block;
    in-out property <bool> brail_bool;
    in-out property <bool> brail_bool_tb;
    in-out property <string> tcfail_block;
    in-out property <bool> tcfail_bool;
    in-out property <bool> tcfail_bool_tb;
    in-out property <string> pfail_block;
    in-out property <bool> pfail_bool;
    in-out property <bool> pfail_bool_tb;
    in-out property <string> blocks_occupied;
    in-out property<string> passengers_boarding: "0";
    in-out property <string> view_block;
    in-out property <string> num_blocks;
    in-out property <string> track_id;
    in-out property <string> block_number;
    in-out property <string> d_traveled;
    in-out property <string> commanded_speed;
    in-out property <string> authority;
    in-out property <string> block_direction;
    in-out property <string> line_type;
    in-out property <string> blocks-occupied-train;

    //block stuff
    in-out property <string> block_underground;
    in-out property <string> block_station;
    in-out property <string> block_crossing;
    in-out property <string> block_switch;
    in-out property <string> block_grade;
    in-out property <string> block_elevation;
    in-out property <string> block_cumulative_elevation;
    in-out property <bool> block_tc_fail;
    in-out property <string> current_tc_fail;
    in-out property <string> current_pfail;
    in-out property <string> current_brail;
    in-out property <bool> block_brail;
    in-out property <bool> block_pfail;
    in-out property <string> block_heater;
    in-out property <string> block_occupied;
    in-out property <string> block_light_color;
    in-out property <string> block_length;
    in-out property <string> crossing_block_tb;
    in-out property <string> switch-block-tb;
    in-out property <string> commanded-speed-block;
    in-out property <string> authority-block;
    in-out property <string> train-authority;
    in-out property <string> train-commanded-speed;

    callback request_update_train_block();
    callback request_update_external_temp();
    callback request_update_passengers_deboarding;
    callback request_update_switch_block();
    callback request_update_crossing_block();
    callback request_update_green_block();
    callback request_update_yellow_block();
    callback request_update_red_block();
    callback request_update_brail_block();
    callback request_update_tcfail_block();
    callback request_update_pfail_block();
    callback request_update_distance_traveled();
    callback request_update_commanded_speed();
    callback request_update_authority();
    callback request_update_pfail_block_tb();
    callback request_update_tc_fail_block_tb();
    callback request_update_brail_block_tb();
    callback request_add_train();

    callback request_block_info();
    
    callback choose-file();
    callback parse-file();
    
    TabWidget{
        Tab{
        title: "Track Model Home";
        HorizontalBox {
        max-width: 500px;
                VerticalBox {
                    Rectangle{
                        preferred-height: 250px;
                        preferred-width: 50px;
                        VerticalBox {
                            HorizontalBox {
                                TrackInput{
                                fileName: selected_fileName;
                                choose-file=>{root.choose-file()}
                                parse-file=>{root.parse-file()}
                                }
                            }
                        VerticalBox {
                            max-height: 5px;
                            HorizontalBox {
                                Image {
                                    source: @image-url("train-icon.png");
                                    height: 50px;
                                    width: 50px;
                                }
                                Text{
                                    y: 0px;
                                    //width: 100px;
                                    //height: 100px;
                                    text: ": " + blocks-occupied-train;
                                    font-size: 25px;
                                    //preferred-width: 250px;                
                                }
                                Image {
                                    source: @image-url("train-icon.png");
                                    height: 50px;
                                    width: 50px;
                                }
                                Text{
                                    y: 0px;
                                    //width: 100px;
                                    //height: 100px;
                                    text: "Heads: " + train-block;
                                    font-size: 25px;
                                    //preferred-width: 250px;
                                }
                            }
                        }

                            HorizontalBox {
                                if track_id=="green" : Image {
                                    source: @image-url("green_line_picture.png");
                                    height: 600px;
                                    width: 700px;
                                    //y: 150px; 
                                    // if train_block<69 && train_block>59 : Image {
                                    //     source: @image-url("/Users/ibrah/Documents/trainscode/trains/ui/train-icon.png");
                                    //     y: 250px;
                                    //     x: (train_block * 2) *1px;
                                    //     height: 50px;
                                    //     width: 50px;
                                    // } 
                                }
                                //if track_id=="red"
                            }
                            // Rectangle { 
                            //     if train_block<69 && train_block>59 : Image {
                            //         source: @image-url("/Users/ibrah/Documents/trainscode/trains/ui/train-icon.png");
                            //         y: 200px;
                            //         x: train_block*1px;
                            //         height: 50px;
                            //         width: 50px;
                            //     }
                            // }
                            // Button {
                            //     text: "Update";
                            //     clicked => {
                            //         root.request_update_train_block();
                            //     }
                            //     min-width: 100px;
                            // }
                        }
                    }
                }
                VerticalBox {
                    Rectangle{
                        preferred-height: 250px;
                        preferred-width: 50px;
                        VerticalBox {
                            HorizontalBox {
                                max-width: 200px;
                                VerticalBox {
                                    Rectangle {
                                        //border-color: white;
                                        //border-radius: 20px;
                                        //border-width: 5px;
                                        preferred-height: 250px;
                                        preferred-width: 50px;
                                        min-height:700px;
                                        VerticalBox {
                                            spacing: 5px; 
                                            //Train BlockId
                                    HorizontalBox {
                                            Text{
                                            text: "Line: " + line_type;
                                            max-width: 150px;
                                            max-height: 30px;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                            }
                                            Text{
                                            text: "Number of blocks:";
                                            max-width: 150px;
                                            max-height: 30px;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                            }
                                            Text {
                                            text: num_blocks;
                                            //max-height: 30px;
                                            //max-width: 150px;
                                            //horizontal-alignment: center;
                                            font-size: 20px;
                                            }
                                        }
                                    HorizontalBox {
                                            Text{
                                            text: "External Temperature:";
                                            max-width: 150px;
                                            max-height: 30px;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                            }
                                            LineEdit {
                                                text: external_temp;
                                                font-size: 20px;
                                                max-width: 30px;
                                                horizontal-alignment: center;
                                                placeholder-text: "Enter Value";
                                                edited(val)=>{external_temp=val}
                                            }
                                            Text {
                                                text: "° Fahrenheit";
                                                vertical-alignment: center;
                                                font-size: 20px;
                                            }
                                            Button {
                                                text: "Confirm";
                                                clicked => {
                                                    root.request_update_external_temp();
                                                }
                                            }

                                    }
                                    HorizontalBox {
                                            Text{
                                                max-width: 150px;
                                                max-height: 30px;
                                                text: "View Info of Block #:";
                                                font-size: 20px;
                                                preferred-width: 250px;
                                            }
                                            LineEdit {
                                            text: block_number;
                                            font-size: 20px;
                                            max-width: 30px;
                                            max-height: 30px;
                                            horizontal-alignment: center;
                                            placeholder-text: "Enter Value";
                                            edited(val)=>{block_number=val}                       
                                            }
                                            Button {
                                                text: "Confirm";
                                                clicked => {
                                                    root.request_block_info();
                                                }
                                                max-width: 100px;
                                            }
                                    }
                                    HorizontalBox {
                                        Text{
                                            max-width: 200px;
                                            max-height: 30px;
                                            text: "Connected to: " + block-switch;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                        Text{
                                            max-width: 150px;
                                            max-height: 30px;
                                            text: "Station: " + block-station;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                        Text{
                                            max-width: 150px;
                                            max-height: 30px;
                                            text: "Crossing: " + block-crossing;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                    }
                                    HorizontalBox {
                                        Text{
                                            max-width: 150px;
                                            max-height: 30px;
                                            text: "Grade: " + block-grade + " %";
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                        Text{
                                            max-width: 40px;
                                            max-height: 30px;
                                            text: "Ticket Sales:";
                                            font-size: 20px;
                                            preferred-width: 40px;
                                        }
                                        if block-station=="YES":
                                        Text{
                                            text: " 200";
                                            font-size: 20px;
                                        }
                                        if block-station=="NO":
                                        Text{
                                            text: " N/A";
                                            font-size: 20px;
                                        }
                                    }
                                    HorizontalBox {
                                        Text{
                                            max-width: 200px;
                                            max-height: 30px;
                                            text: "Elevation: " + block-elevation + " Feet";
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                        Text{
                                            max-width: 150px;
                                            max-height: 30px;
                                            text: "Cumulative Elevation: " + block-cumulative-elevation + " Feet";
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                    }
                                    // HorizontalBox {
                                    //     Text{
                                    //         max-width: 150px;
                                    //         max-height: 30px;
                                    //         text: "Cumulative Elevation: " + block-cumulative-elevation + " Feet";
                                    //         font-size: 20px;
                                    //         preferred-width: 250px;
                                    //     }
                                    // }
                                    HorizontalBox {
                                        Text{
                                            max-width: 150px;
                                            max-height: 30px;
                                            text: "Track Circuit Failure: " + current-tc-fail;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                        Switch {
                                            checked: tcfail_bool;
                                            toggled => {tcfail_bool = !tcfail_bool;}
                                        }
                                        Button {
                                            text: "Confirm ";
                                            clicked => {
                                                root.request_update_tcfail_block();
                                            }
                                            max-width: 100px;
                                        }
                                    }
                                    HorizontalBox {
                                        Text{
                                            max-width: 100px;
                                            max-height: 30px;
                                            text: "Broken Rail: " + current-brail;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                        Switch {
                                            checked: brail_bool;
                                            toggled => {brail_bool = !brail_bool;}
                                        }
                                        Button {
                                            text: "Confirm";
                                            clicked => {
                                                root.request_update_brail_block();
                                            }
                                            min-width: 100px;
                                        }
                                        Text{
                                            max-width: 100px;
                                            max-height: 30px;
                                            text: "Power Failure: " + current-pfail;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                        Switch {
                                            checked: pfail_bool;
                                            toggled => {pfail_bool = !pfail_bool;}
                                        }
                                        Button {
                                            text: "Confirm";
                                            clicked => {
                                                root.request_update_pfail_block();
                                            }
                                            min-width: 100px;
                                        }
                                    }
                                    HorizontalBox {
                                        Text{
                                            max-width: 150px;
                                            max-height: 30px;
                                            text: "Occupied: " + block-occupied;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                        Text{
                                            max-width: 175px;
                                            max-height: 30px;
                                            text: "Underground: " + block-underground;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                        Text{
                                            max-width: 150px;
                                            max-height: 30px;
                                            text: "Heater: " + block-heater;
                                            font-size: 20px;
                                            preferred-width: 250px;
                                        }
                                    }
                                    HorizontalBox {
                                            Text{
                                                max-width: 150px;
                                                max-height: 30px;
                                                text: "Light Color: " + block-light-color;
                                                font-size: 20px;
                                                preferred-width: 250px;
                                            }
                                        }
                                        HorizontalBox {
                                            Text{
                                                max-width: 150px;
                                                max-height: 30px;
                                                text: "Block Length: " + block-length + " Feet";
                                                font-size: 20px;
                                                preferred-width: 250px;
                                            }
                                        }
                                        HorizontalBox {
                                            Text{
                                                max-width: 150px;
                                                max-height: 30px;
                                                text: "Direction: " + block_direction;
                                                font-size: 20px;
                                                preferred-width: 250px;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

            /*popup:= PopupWindow {
                Rectangle {
                    height:100%; width: 100%; background: white;
                } 
                height: 300px;
                width: 300px;
                x: 600px;
            }*/

            // HorizontalBox {
            //     alignment: end;
            //         Button{
            //             text: "TestBench";
            //             clicked => {
            //                 popup.show();
            //             }
            //     }
            // }

            preferred-height: 800px;
            preferred-width: 800px;
        }
        Tab{
            title: "Track Model Test Bench";
            HorizontalBox {

                VerticalBox {
                    Text{
                    text: "INPUTS";
                    font-size: 30px;
                    horizontal-alignment: center;
                    }

                    Rectangle {
                        //border-color: white;
                        //border-radius: 20px;
                        //border-width: 5px;
                        preferred-height: 250px;
                        preferred-width: 50px;
                        min-height:700px;
                        VerticalBox {
                            spacing: 5px; 
                            //Train BlockId
                            HorizontalBox {
                                Text {
                                    text: "Add Train:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_add_train();
                                    }
                                   // min-width: 100px;
                                }
                            }
                            HorizontalBox {
                                Text {
                                    text: "Distance Traveled:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: d_traveled;
                                    font-size: 20px;
                                    horizontal-alignment: center;
                                    placeholder-text: "Enter Value";
                                    edited(val)=>{d_traveled=val}
                                }
                                Text {
                                    text: "Meters on Train #:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                }
                                LineEdit {
                                    text: train_id;
                                    font-size: 20px;
                                    horizontal-alignment: center;
                                    placeholder-text: "Enter Value";
                                    edited(val)=>{train_id=val}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_distance_traveled();
                                    }
                                    min-width: 100px;
                                }
                            }
                            //External temp
                            HorizontalBox {
                                Text {
                                    text: "External Temperature:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: external_temp;
                                    font-size: 20px;
                                    horizontal-alignment: center;
                                    placeholder-text: "Enter Value";
                                    edited(val)=>{external_temp=val}
                                }
                                Text {
                                    text: "° Fahrenheit";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_external_temp();
                                    }
                                    min-width: 100px;
                                }
                            }
                            //Commanded Speed
                            HorizontalBox {
                                Text {
                                    text: "Commanded Speed:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: commanded-speed;
                                    font-size: 20px;
                                    horizontal-alignment: center;
                                    placeholder-text: "Enter Value";
                                    edited(val)=>{commanded_speed=val}
                                }
                                Text {
                                    text: "m/s on Block: ";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                }
                                LineEdit {
                                    text: commanded-speed-block;
                                    font-size: 20px;
                                    horizontal-alignment: center;
                                    placeholder-text: "Enter Value";
                                    edited(val)=>{commanded_speed_block=val}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_commanded_speed();
                                    }
                                    min-width: 100px;
                                }
                            }
                            //Authority
                            HorizontalBox {
                                Text {
                                    text: "Authority:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: authority;
                                    font-size: 20px;
                                    horizontal-alignment: center;
                                    placeholder-text: "Enter Value";
                                    edited(val)=>{authority=val}
                                }
                                Text {
                                    text: "Blocks on Block: ";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                }
                                LineEdit {
                                    text: authority-block;
                                    font-size: 20px;
                                    horizontal-alignment: center;
                                    placeholder-text: "Enter Value";
                                    edited(val)=>{authority_block=val}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_authority();
                                    }
                                    min-width: 100px;
                                }
                            }
                            //Passengers deboarding
                            HorizontalBox {
                                Text {
                                    text: "Passengers Deboarding:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: passengers_deboarding;
                                    font-size: 20px;
                                    horizontal-alignment: center;
                                    placeholder-text: "Enter Value";
                                    edited(val)=>{passengers_deboarding=val}
                                }
                                Text {
                                    text: "Passengers";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_passengers_deboarding();
                                    }
                                    min-width: 100px;
                                }
                            }
                            //Switch State
                            HorizontalBox {
                                Text {
                                    text: "Switch Block:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: switch-block-tb;
                                    font-size: 20px;
                                    placeholder-text: "Enter Value";
                                    horizontal-alignment: center;
                                    edited(val)=>{switch-block-tb=val} 
                                }
                                Switch {
                                    checked: switch_bool;
                                    toggled => {switch_bool = !switch_bool;}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_switch_block();
                                    }
                                    min-width: 100px;
                                }
                            }
                            //Crossing State Block
                            HorizontalBox {
                                Text {
                                    text: "Crossing Block:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: crossing_block_tb;
                                    font-size: 20px;
                                    placeholder-text: "Enter Value";
                                    horizontal-alignment: center;
                                    edited(val)=>{crossing-block-tb=val}    
                                }
                                Switch {
                                    checked: crossing_bool;
                                    toggled => {crossing_bool = !crossing_bool;}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_crossing_block();
                                    }
                                    min-width: 100px;
                                }
                            }
                            //GREEN LIGHT
                            HorizontalBox {
                                Text {
                                    text: "Green Traffic Light Block:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    //text: root.external_temp;
                                    font-size: 20px;
                                    placeholder-text: "Enter Value";
                                    horizontal-alignment: center;
                                    edited(val)=>{green-block=val}   
                                    
                                }
                                Switch {
                                    checked: green_bool;
                                    toggled => {green_bool = !green_bool;}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_green_block();
                                    }
                                    min-width: 100px;
                                }
                            }
                            //Yellow Traffic Light
                            HorizontalBox {
                                Text {
                                    text: "Yellow Traffic Light Block:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    //text: root.external_temp;
                                    font-size: 20px;
                                    placeholder-text: "Enter Value";
                                    horizontal-alignment: center;
                                    edited(val)=>{yellow-block=val}   
                                    
                                }
                                Switch {
                                    checked: yellow_bool;
                                    toggled => {yellow_bool = !yellow_bool;}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_yellow_block();
                                    }
                                    min-width: 100px;
                                }
                            }
                            //Red Traffic Light
                            HorizontalBox {
                                Text {
                                    text: "Red Traffic Light Block:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    //text: root.external_temp;
                                    font-size: 20px;
                                    placeholder-text: "Enter Value";
                                    horizontal-alignment: center;
                                    edited(val)=>{red-block=val}   
                                    
                                }
                                Switch {
                                    checked: red_bool;
                                    toggled => {red_bool = !red_bool;}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_red_block();
                                    }
                                    min-width: 100px;
                                }
                            }
                             //Broken Rail
                             HorizontalBox {
                                Text {
                                    text: "Break Rail on Block:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: brail_block;
                                    font-size: 20px;
                                    placeholder-text: "Enter Value";
                                    horizontal-alignment: center;
                                    edited(val)=>{brail_block=val}
                                }
                                Switch {
                                    checked: brail_bool_tb;
                                    toggled => {brail_bool_tb = !brail_bool_tb;}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_brail_block_tb();
                                    }
                                    min-width: 100px;
                                }
                            }
                             //TC Fail
                             HorizontalBox {
                                Text {
                                    text: "Fail Track Circuit on Block:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: tcfail_block;
                                    font-size: 20px;
                                    placeholder-text: "Enter Value";
                                    horizontal-alignment: center;
                                    edited(val)=>{tcfail_block=val}
                                }
                                Switch {
                                    checked: tcfail_bool_tb;
                                    toggled => {tcfail_bool_tb = !tcfail_bool_tb;}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_tc_fail_block_tb();
                                    }
                                    min-width: 100px;
                                }
                            }
                             //Power fail
                             HorizontalBox {
                                Text {
                                    text: "Fail Power on Block:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: pfail_block;
                                    font-size: 20px;
                                    placeholder-text: "Enter Value";
                                    horizontal-alignment: center;
                                    edited(val)=>{pfail_block=val}
                                    
                                }
                                Switch {
                                    checked: pfail_bool_tb;
                                    toggled => {pfail_bool_tb = !pfail_bool_tb;}
                                }
                                Button {
                                    text: "Confirm";
                                    clicked => {
                                        root.request_update_pfail_block_tb();
                                    }
                                    min-width: 100px;
                                }
                            }
                        }
                    }
                }
                VerticalBox {
                    Text{
                    text: "SIMULATED OUTPUTS";
                    font-size: 30px;
                    horizontal-alignment: center;
                    }
                    Rectangle {
                        //border-color: white;
                        //border-radius: 20px;
                        //border-width: 5px;
                        preferred-height: 250px;
                        preferred-width: 50px;
                        min-height:700px;
                        VerticalBox {
                            spacing: 5px; 
                            //OCCUPANCY
                            HorizontalBox {
                                Text {
                                    text: "Blocks Occupied:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                TextEdit {
                                    text: blocks_occupied;
                                    max-height: 200px;
                                    horizontal-alignment: center;
                                    font-size: 20px;
                                    read-only: true;
                                    //horizontal-alignment: center;
                                    //vertical-alignment: center;
                                }
                            }
                            //Passengers boarding
                            HorizontalBox {
                                Text {
                                    text: "Passengers Boarding:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: passengers_boarding;
                                    font-size: 20px;
                                    max-height: 200px;
                                    horizontal-alignment: center;
                                    read-only: true;
                                    //vertical-alignment: center;
                                }
                                Text {
                                    text: "Passengers";
                                    vertical-alignment: center;
                                    horizontal-alignment: left;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                            }
                            //Authority
                            HorizontalBox {
                                Text {
                                    text: "Authority:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: train_authority;
                                    font-size: 20px;
                                    max-height: 200px;
                                    horizontal-alignment: center;
                                    read-only: true;
                                    //vertical-alignment: center;
                                }
                                Text {
                                    text: "Blocks";
                                    vertical-alignment: center;
                                    horizontal-alignment: left;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                            }
                            //Commanded Speed
                            HorizontalBox {
                                Text {
                                    text: "Commanded Speed:";
                                    vertical-alignment: center;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                                LineEdit {
                                    text: train-commanded-speed;
                                    font-size: 20px;
                                    max-height: 200px;
                                    horizontal-alignment: center;
                                    read-only: true;
                                    //vertical-alignment: center;
                                }
                                Text {
                                    text: "m/s";
                                    vertical-alignment: center;
                                    horizontal-alignment: left;
                                    font-size: 20px;
                                    preferred-width: 250px;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

