import { HorizontalBox, VerticalBox, Button } from "std-widgets.slint";

export component WaysideControllerUi inherits Window {
    in-out property <string> time: "00:00:00";
    title: "Wayside Controller";
    HorizontalBox {
        padding: 50px;
        VerticalBox {
            Text {
                text: "This is the Wayside Controller UI.";
            }

            Text {
                text: "Time: \{root.time}";
            }
        }
    }
}
