import {Palette, GridBox, TabWidget, ComboBox, Button, ProgressIndicator, Switch, VerticalBox, ListView, Spinner, SpinBox, HorizontalBox, LineEdit} from "std-widgets.slint";

//database view component
export component TableView inherits Rectangle {
    in property <[string]> columns;
    in property <[[string]]> values;

    private property <length> e: self.width / root.columns.length;
    private property <[length]> column_sizes: [
        root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e,
        root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e,
        root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e, root.e,
    ];

    VerticalBox {
        padding: 5px;
        HorizontalLayout {
            padding: 3px; spacing: 3px;
            vertical-stretch: 0;
            for title[idx] in root.columns : HorizontalLayout {
                width: root.column_sizes[idx];
                Text { overflow: elide; text: title; color: black; }
                Rectangle {
                    width: 1px;
                    background: gray;
                    TouchArea {
                        width: 10px;
                        x: (parent.width - self.width) / 2;
                        property <length> cached;
                        pointer-event(event) => {
                            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                                self.cached = root.column_sizes[idx];
                            }
                        }
                        moved => {
                            if (self.pressed) {
                                root.column_sizes[idx] += (self.mouse-x - self.pressed-x);
                                if (root.column_sizes[idx] < 0) {
                                    root.column_sizes[idx] = 0;
                                }
                            }
                        }
                        mouse-cursor: ew-resize;
                    }
                }
            }
        }
        ListView {
            for r in root.values : HorizontalLayout {
                padding: 3px;
                spacing: 3px;
                for t[idx] in r : HorizontalLayout {
                    width: root.column_sizes[idx];
                    Text { overflow: elide; text: t; }
                }
            }
        }
    }
}

//generic track component
export component StraightTrack inherits Path {
    width: 75px;
    height: 25px;
    commands: "M 0 0 L 100 0";  // A straight line from (0, 0) to (100, 0)
    stroke: black;
    stroke-width: 2px;
}

//enter filename field for custom PLC
export component EnterFilename inherits Window {
    width: 200px;
    height: 25px;
    LineEdit {
        font-size: 14px;
        width: parent.width;
        height: parent.height;
        placeholder-text: "Enter Filename here";
    }
}

// signal light component
export component TrafficLight inherits Rectangle {
    // Define the states for the traffic light

    // Define the size of the traffic light
    preferred-width: 100px;
    preferred-height: 250px;
    border-width:1px;
    border-color: black;

    // Layout for the traffic light
    VerticalBox {
        spacing: 5px;
        padding: 10px;
    
        // Red light
        Rectangle {
            property<bool> active: true;
            TouchArea {
                clicked=> {active = !active}
            }
            width: 80px;
            height: 80px;
            border-radius: root.width;// Circular
            //background: red;
            //brush: state == 0 ? red : darkgray; // Red light
            states [
                on when active : {
                    background: red;
                }
                
                off when !active : {
                    background: gray;
                }
            ]
        }
    
        // Green light
        Rectangle {
            property<bool> active: true;
            TouchArea {
                clicked=> {active = !active}
            }
            states [
                on when active : {
                    background: green;
                }
                
                off when !active : {
                    background: gray;
                }
            ]
            width: 80px;
            height: 80px;
            border-radius: root.width;// Circular
            //background: green;
            //brush: state == 2 ? green : darkgray; // Green light
        }


    }
}

//baseline track switch component
export component TrackSwitch inherits Rectangle {
    property<bool> active: false;

    VerticalBox {
        Rectangle {
            property<int> y_val: 25;
            animate y_val {
                duration: 500ms;
            }

            height: 100px;
            width: 250px;

            StraightTrack {
                x:19px;
                y: 44px; 
             }
             StraightTrack {
                x:154px;
                y: 60px;
             }
             StraightTrack {
                x:154px;
                y: 24px;
             }

            TouchArea {
                clicked => { active = !active }

                Path {
                    viewbox-height: parent.height / 1px;
                    viewbox-width: parent.width / 1px;
                    x: 116px;
                    y: 3px;
                    width: 206px;
                    fill-rule: FillRule.nonzero;
                    height: 180px;
                    stroke: red;
                    stroke-width: 2px;

                    mt := MoveTo {
                        x: 50;
                        y: y_val;
                    }
                    lt := LineTo {
                        x: -30;
                        y: 5;
                    }
                    Close {}
                }
            }

            states [
                on when active : {
                    background: lightyellow;
                    y_val: -20;
                }

                off when !active : {
                    background: lightblue;
                    y_val: 25;
                }
            ]
        }

        // Text caption outside the rectangle
        txt := Text {
            horizontal-alignment: left;
            vertical-alignment: top;  // Adjust to position above the rectangle
            color: black;
            text: "switch";  // Default text

            states [
                on when active: {
                    color: black;
                    text: "switch open";  // Change text when active
                }
                off when !active: {
                    color: black;
                    text: "switch closed";  // Change text back when inactive
                }
            ]
        }
    }
}


//shows block occupancy, crossing status and station name
export component BlockInfo inherits Rectangle {
    // Define the states for the traffic light

    // Define the size of the traffic light
    preferred-width: 200px;
    preferred-height: 300px;
    
    
    VerticalLayout {
        // Layout for the traffic light
            HorizontalBox {
                spacing: 105px;
                padding: 10px;

                // Red light
                Rectangle {
                    property<bool> active: true;
                    TouchArea {
                        clicked=> {active = !active}
                        Text {
                            horizontal-alignment: TextHorizontalAlignment.left;
                            text: "crossing state";
                        }
                    }
                    width: 80px;
                    height: 80px;
                    border-radius: root.width;// Circular
                    //background: red;
                    //brush: state == 0 ? red : darkgray; // Red light
                    states [
                        on when active : {
                            background: red;
                        }
                        
                        off when !active : {
                            background: green;
                        }
                    ]
                }
            
                // Green light
                Rectangle {
                    property<bool> active: true;
                    TouchArea {
                        clicked=> {active = !active}
                        Text {
                            horizontal-alignment: TextHorizontalAlignment.right;
                            text: "block occ";
                        }
                    }
                    states [
                        on when active : {
                            background: red;
                        }
                        
                        off when !active : {
                            background: green;
                        }
                    ]
                    width: 80px;
                    height: 80px;
                    border-radius: root.width;// Circular
                    //background: green;
                    //brush: state == 2 ? green : darkgray; // Green light
                }

                //Station Name
                Rectangle {
                    width: 100px;
                    height: 50px;
                    y: 10px;
                    background: lightgray;
                    padding: 5px;
                    
                    Text{
                        text: "Station Name";
                        color: black;
                    }
                }



            }
        }
}



////////////////////////////////////////////////

// main window
export component WaysideControllerUi inherits Window {
        title: "Wayside Controller";
        min-height: 500px;
        min-width: 700px;
        in-out property <int> active-tab;
        VerticalLayout {
            tab_bar := HorizontalLayout {
                spacing: 3px;
                Button {
                    text: "PLC";
                    clicked => { root.active-tab = 0; }
                }
                Button {
                    text: "Block Status";
                    clicked => { root.active-tab = 1; }
                }
                Button {
                    text: "TESTBENCH";
                    clicked => { root.active-tab = 2; }
                }
                ComboBox {
                    width: self.preferred-width;
                    height: self.preferred-height * 2;
                    model: ["Software Wayside Controller", "Hardware Wayside Controller"];
                    current-value: "Software Wayside Controller";
                }
            }
            Rectangle {
                Rectangle {

                    //animations to enter page
                    background: black;
                    drop-shadow-blur: 0cm;
                    x: root.active-tab == 0 ? 0 : root.active-tab < 0 ? - self.width - 1px : parent.width + 1px;
                    animate x { duration: 125ms; easing: ease; }

                    //page contents
                    ComboBox {
                        model: ["PLC 1", "PLC 2", "PLC 3"];
                        x: 57px;
                        y: 120px;
                    }
                    EnterFilename {
                        //accessible-role: AccessibleRole.checkbox;
                        //text: "File Upload";
                        x: 52px;
                        y: 196px;
                        //clicked => { self.text = "File Uploading";}
                    }
                    ProgressIndicator { 
                        width: 150px;
                        x: 61px;
                        y: 273px;
                        height: 20px;
                        progress: 50%;
                    }
                    Spinner {
                        progress: 50%;
                        x: 449px;
                        y: 193px;
                    }
                }
                Rectangle {
                    background: black;
                    x: root.active-tab == 1 ? 0 : root.active-tab < 1 ? - self.width - 1px : parent.width + 1px;
                    animate x { duration: 125ms; easing: ease; }

                    TrafficLight {
                        width: self.preferred-width;
                        height: self.preferred-height / 1.35;
                        x: 57px;
                        y: 120px;
                           
                        }
                    TrackSwitch {
                        x: 263px;
                        y: 120px;
                    }
                    BlockInfo {
                        x: 61px;
                        y: 350px;
                        
                    }
                    
                }

                Rectangle {
                    background: black;
                    x: root.active-tab == 2 ? 0 : root.active-tab < 2 ? - self.width - 1px : parent.width + 1px;
                    animate x { duration: 125ms; easing: ease; }

                    TableView {
                        columns: ["Device", "Mount Point", "Total", "Free", "Track Number", "Test"];
                        values: [
                            ["/dev/sda1", "/", "255GB", "82.2GB"] ,
                            ["/dev/sda2", "/tmp", "60.5GB", "44.5GB"] ,
                            ["/dev/sdb1", "/home", "255GB", "32.2GB"] ,
                            ["/dev/sdb1", "/home", "255GB", "32.2GB"] ,
                        ];
                    }
            }
        }
    }
}
