import {Palette, StandardTableView, TextEdit, ScrollView, GridBox, TabWidget, ComboBox, Button, ProgressIndicator, Switch, VerticalBox, ListView, Spinner, SpinBox, HorizontalBox, LineEdit} from "std-widgets.slint";

//enter filename field for custom PLC
export component EnterFilename inherits Window {

    in-out property <string> plcprog;
    callback select_file();
    callback parse_file();

    width: 153px;
    height: 27px;
    x: 163px;
    y: 52px;
    LineEdit {
        font-size: 14px;
        width: parent.width;
        height: parent.height;
        placeholder-text: "Enter filename";

        edited(input) => {plcprog = input}

    }
    Button {

        text: "Load PLC";
        x: 190px;
        clicked => {parse_file()}

    }
}

//table view SW - DEFAULT
component BlockLayoutMap inherits Rectangle {
    background: #252525;
    border-radius: 10px;
    preferred-height: 180px;
    in-out property <[[StandardListViewItem]]> block_data;
    in-out property <string> section;
    in-out property <string> block;
    in-out property <bool> mode: true;
    in-out property <bool> crossing: true;
    in-out property <bool> signal: true;

    in-out property <bool> switch: false;
    in-out property <bool> occupancy: false;
    in-out property <string> failure;
    VerticalLayout {

        ScrollView{
            height: 250px;
            viewport-width: 675px;
            viewport-height: 500px;

        VerticalLayout {
            padding: 15px;
            StandardTableView {
                columns: [
                    { title: @tr("Section") },
                    { title: @tr("Block") },
                    { title: @tr("Occupancy") },
                    { title: @tr("Crossing") },
                    { title: @tr("Signal State") },
                    { title: @tr("Switch State") },
                ];
                rows: block_data;
            }
        }
    }
        ManageBlock := HorizontalLayout {
            alignment: start;
            padding: 15px;
            spacing: 10px;
            LineEdit {
                width: 130px;
                height: 30px;
                placeholder-text: @tr("Block Line, Number");
                edited(input) => { section = input }
            }
            LineEdit {
                width: 130px;
                height: 30px;
                placeholder-text: @tr("Switch Orientation");
                edited(input) => { section = input }
            }
            HorizontalLayout {
                Switch {
                    toggled => {mode = !mode}
                }
                Text {text:"  Occupancy"; y: 7px;}
            }
            HorizontalLayout {
                Switch {
                    toggled => {crossing = !crossing}
                }
                Text {text:" Crossing"; y: 7px;}
            }
            HorizontalLayout {
                Switch {
                    toggled => {signal = !signal}
                }
                Text {text:"  Signal"; y: 7px;}
            }
            
        }
    }
}

//combo 1 - SW vs HW WC
export component WCType inherits ComboBox {

    in-out property <string> sworhw;
    in-out property <bool> selectWayside: true;
    callback selectWCType();

    width: self.preferred-width;
    x: 400px;
    y: 50px;
    height: self.preferred-height * 2;
    model: ["Software Wayside Controller", "Hardware Wayside Controller"];
    current-value: "Software Wayside Controller";

    selected(item) => {
        sworhw = item;

        if(item == "Software Wayside Controller"){
            selectWayside = true;
        } else if(item == "Hardware Wayside Controller"){
            selectWayside = false;
        }
    }


    
}
//combo 2 - Redline vs Greenline
export component LineType inherits ComboBox {
 
    in-out property <string> redorgreen;
    in-out property <bool> selectLine: true;

    callback selectLineType();

    width: self.preferred-width;
    x: 625px;
    y: 50px;
    height: self.preferred-height * 2;
    model: ["Green Line", "Red Line"];
    current-value: "Green Line";

    selected(item) => {
        redorgreen = item;

        if(item == "Software Wayside Controller"){
            selectLine = true;
        } else if(item == "Hardware Wayside Controller"){
            selectLine = false;
        }
    }


}
//show button
export component ShowButton inherits Button {
    
    callback load_block_data();

    text: "Show Track Blocks";
    x: 499px;
    y: 100px;

    
}

////////////////////////////////////////////////

// main window
export component WaysideControllerUi inherits Window {

        //test bench//

        
        //generic time var
        in-out property <string> time;

        in-out property <int> active_tab;
        in-out property <string> pick_file;

        //variables string input
        in-out property <string> sugg_spd;
        in-out property <string> sugg_auth;
        

        //variables output
        in-out property <float> comm_spd;
        in-out property <string> comm_auth;

        
        in-out property <string> str_plc_prog;
        in-out property <string> str_plc_progin;
        in-out property <string> plc_prog;

        in-out property <string> str_block_main;
        in-out property <string> str_block_mainin;
        in-out property <bool> block_main;

        in-out property <string> str_sw_state;
        in-out property <string> str_sw_statein;
        in-out property <bool> sw_state;

        in-out property <string> str_block_occ;
        in-out property <string> str_block_occin;
        in-out property <bool> block-occ;

        in-out property <string> str_track_fail;
        in-out property <bool> track_fail;

        //output callbacks
        callback disp_sugg_spd();
        callback disp_sugg_auth();
        callback disp_maintenance_md();
        callback disp_sw_state();
        callback disp_block_occ();
        callback disp_select_plc();
        callback disp_parse_file();

        callback clicked();

        //test bench//

        //selecting wayside controller and line
        in-out property <string> sworhw;
        in-out property <string> redorgreen;
        in-out property <bool> selectLine;
        in-out property <bool> selectWayside;
        callback selectWCType();
        callback selectLineType();

        //generic active
        //in-out property <int> active_tab;

        //entering a filename for PLC
        in-out property <string> plcprog;
        callback select_file();
        callback parse_file();

        //switching between HW and SW wayside table view
        in-out property <[[StandardListViewItem]]> block_data;
        callback load_block_data();

        //filling table
        in-out property <string> section;
        in-out property <string> block;
        in-out property <bool> mode: true;
        in-out property <bool> crossing: true;
        in-out property <bool> signal: true;
    
        in-out property <bool> switch: false;
        in-out property <bool> occupancy: false;
        in-out property <string> failure;
        
        //fill w SW or HW info
        callback fillBlockData();

        title: "Wayside Controller";
        preferred-width: 808px;
        preferred-height: 500px;

        //tabs
        VerticalLayout {
            tab_bar := HorizontalLayout {
                
                spacing: 3px;
                Button {
                    text: "Wayside Controller Homepage";
                    clicked => { root.active-tab = 0; }
                }
                Button {
                    text: "TESTBENCH";
                    clicked => { root.active-tab = 1; }
                }

            }

        Rectangle {
            //animations to enter page
            drop-shadow-blur: 0cm;
            x: root.active-tab == 0 ? 0 : root.active-tab < 0 ? - self.width - 1px : parent.width + 1px;
            animate x { duration: 125ms; easing: ease; }

            ScrollView{
                height: 400px;
                viewport-width: 300px;
                viewport-height: 700px;
            
                Text {
                    text: "Enter PLC filename";  // Default text
                    color: green;
                    x: 108px;
                    y: 26px;
                  }

            EnterFilename {
                x: 35px;
                y: 55px;
                plcprog <=> plcprog;
                select_file => {root.select_file();}
                parse_file => {root.parse_file()}                                
            }

            ProgressIndicator { 
                width: 253px;
                x: 50px;
                y: 100px;
                height: 20px;
                //progress: 50%;
                animate progress {

                }
            }

            Text {
                text: "Select Wayside Controller and Track Line to see block inform";  // Default text
                color: green;
                x: 400px;
                y: 25px;
              }
            WCType{
                
                sworhw <=> sworhw;

            }
            LineType {
                
                redorgreen <=> redorgreen;
            }
            ShowButton {
                text: "Show Track Blocks";
                x: 499px;
                y: 100px;

               clicked => {load_block_data()}
            }

        ///////////// former second tab - converted into a table

        BlockLayoutMap {
        width: 678px;
        x: 50px;
        y: 200px;
      
        } // Transit System Top Widget  
        
        
    } ///
    



////////////////////TESTBENCH INPUTS////////////////////////////////////////


    Rectangle {
        x: root.active-tab == 2 ? 0 : root.active-tab < 2 ? - self.width - 1px : parent.width + 1px;
        animate x { duration: 125ms; easing: ease; }

        HorizontalLayout {
            padding: 10px;
            spacing: 10px;
            Rectangle {
                background: #252525;
                border-radius: 10px;
                VerticalLayout {
                    padding: 10px;
                    padding-left: 15px;
                    Text {text: "Inputs";}
                    
                    VerticalLayout {
                        spacing: 10px;
                        padding: 10px;

                        // Speed Input
                        HorizontalLayout {
                            //alignment: start;
                            Text { text: "Suggested Speed (CTC): ";}
                            Rectangle {width: 10px;}
                            LineEdit {
                                text: sugg-spd;
                                width: 120px;
                                height: 30px;
                                edited(val)=>{
                                    sugg-spd=val}
                            } 
                            
                        Button{
                            text: "Set Speed";
                            clicked => {
                                root.disp-sugg-spd();
                            }}
                        }

                        // Authority Input 
                        HorizontalLayout {
                            //alignment: start;
                            Text { text: "Authority (CTC): ";}
                            Rectangle {width: 10px;}
                            LineEdit {
                            text: sugg-auth;
                            width: 120px;
                            height: 30px;
                            edited(val)=>{sugg-auth=val}
                            }
                            Button{
                                text: "Enter Authority";
                                clicked => {
                                    root.disp_sugg_auth();
                                }}
                        }
                        //Block Maintenance Mode
                        HorizontalLayout {
                            //alignment: start;
                            Text { text: "Block Maintenance (CTC): ";}
                            Rectangle {width: 10px;}
                            LineEdit {
                            text: str_block_mainin;
                            width: 120px;
                            height: 30px;
                            edited(val)=>{str_block_mainin=val}
                            }
                            Button{
                                text: "Enter Maintenance\nMode";
                                clicked => {
                                    root.disp-sw-state();
                                }}
                        }
                        //Switch State
                        HorizontalLayout {
                            //alignment: left;
                            Text { text: "Switch State (CTC): ";}
                            Rectangle {width: 10px;}
                            LineEdit {
                            text: str_sw_statein;
                            width: 120px;
                            height: 30px;
                            edited(val)=>{str_sw_statein=val}
                            }
                            Button{
                                text: "Change Switch";
                                clicked => {
                                    root.disp-sw-state();
                                }}
                        }

                        //Block Occupancy
                        HorizontalLayout {
                            Text { text: "Block Occupancy (Track Model): ";}
                            Rectangle {width: 10px;}
                            LineEdit {
                            text: str_block_occin;
                            width: 120px;
                            height: 30px;
                            edited(val)=>{str_block_occin=val}
                            }
                            Button{
                                text: "Block Occupied";
                                clicked => {
                                    root.disp-sw-state();
                                }}
                        }

                    }
                }
            } 



            ////////////////////////TESTBENCH OUTPUTS////////////////////////////////////


                HorizontalLayout {
                    Rectangle {
                        background: #252525;
                        border-radius: 10px;
                        VerticalLayout {
                            padding: 10px;
                            padding-right: 2px;
                            Text {text: "Outputs";}
                            
                            VerticalLayout {
                                spacing: 10px;
                                padding: 10px;

                                // Speed Input
                                HorizontalLayout {
                                    Text { vertical-alignment: center;
                                        text: "Commanded Speed: ";}
                                        LineEdit {
                                            read-only: true;
                                            min-height: 30px;
                                            max-height: 30px;
                                            text: sugg-spd + " mph";
                                        } 
                                }

                                // Authority Output 
                                HorizontalLayout {
                                    //alignment: start;
                                    Text { vertical-alignment: center;
                                        text: "Commanded Authority: ";}
                                    LineEdit {
                                        read-only: true;
                                        min-height: 30px;
                                        max-height: 30px;
                                        text: comm_auth + " mi";
                                    } 
                                }

                                //Block Maintenance Mode
                                HorizontalLayout {
                                    //alignment: start;
                                    Text { vertical-alignment: center;
                                        text: "Block Maintenance (CTC): ";}
                                    LineEdit {
                                        min-height: 30px;
                                        max-height: 30px;
                                        text: str_block_main;
                                        read-only: true;
                                    } 
                                }

                                //Switch State Mode
                                HorizontalLayout {
                                    //alignment: start;
                                    Text { vertical-alignment: center;
                                        text: "Switch State: ";}
                                    LineEdit {
                                        //read-only: true;
                                        min-height: 30px;
                                        max-height: 30px;
                                        text: str_sw_state;
                                        read-only: true;
                                    }
                                }

                                //Block Occupancy
                                HorizontalLayout {
                                    //alignment: start;
                                    Text { vertical-alignment: center;
                                        text: "Block Occupancy: ";}
                                    LineEdit {
                                        read-only: true;
                                        min-height: 30px;
                                        max-height: 30px;
                                        text: str_block_occ;
                                    }
                                }

                                //PLC Program
                                HorizontalLayout {
                                    //alignment: start;
                                    Text { vertical-alignment: center;
                                        text: "PLC Program: ";}
                                    LineEdit {
                                        read-only: true;
                                        min-height: 30px;
                                        max-height: 30px;
                                        text: str_plc_prog;
                                    }
                                }

                                //Track Failure
                                HorizontalLayout {
                                    Text { vertical-alignment: center;
                                        text: "Track Failure: ";}
                                    LineEdit {
                                        read-only: true;
                                        min-height: 30px;
                                        max-height: 30px;
                                        text: str_track_fail;
                                    }
                                }

                            }
                        }
                    } 
                } 
            }
        }
            
    }
}
}